CREATE TABLE DIRECTIONS(
DIRECTION_NAME VARCHAR(50),
ROUTE_ID VARCHAR(5) NOT NULL,
ROUTE_TYPE VARCHAR(1) NOT NULL,
DIRECTION_ID VARCHAR(5) NOT NULL,
CONSTRAINT DIRECTIONS_PX PRIMARY KEY (ROUTE_ID,ROUTE_TYPE,DIRECTION_ID)
);