CREATE TABLE ROUTES(
ROUTE_TYPE VARCHAR(1) NOT NULL,
ROUTE_ID VARCHAR(5) NOT NULL,
ROUTE_NAME VARCHAR(50) NOT NULL,
ROUTE_NUMBER VARCHAR(4) NOT null,
CONSTRAINT ROUTES_PX PRIMARY KEY (ROUTE_ID,ROUTE_NUMBER)
);